from handlers import client
from handlers import admin
from handlers import other
from handlers import _create_entry
from handlers import _email
from handlers import _start
from handlers import _report
from handlers import _delete_entry
from handlers import _edit_entry
from handlers import _report_mail
